### ISSUE TITLE
ERROR: pull access denied for iris-api

### ISSUE THREAD

**Issue by jmatsushita** [jrgp/iris-docker-compose#1]
Running make fails with this error:
```
Pulling iris-api (iris-api:latest)...
ERROR: pull access denied for iris-api, repository does not exist or may require 'docker login'
```

Changing `image: iris-api` in the `docker-compose.yml` to:
```
  iris-api:
    depends_on:
      - db
    # build: ./iris-api
    image: quay.io/iris/iris
```

Solves the problem.
